version: '3.8'

services:
  tracking-ms:
    image: ghcr.io/monitoring-tool-app-unicauca/monitoring-tool-backend-tracking-ms:latest
    ports:
      - "8092:8092"
    environment:
      TZ: America/Bogota
      SPRING_PROFILES_ACTIVE: "docker"
      TRACKING_PORT: 8092
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: monitoring_db
      DB_USERNAME: monitoring-user
      DB_PASSWORD: monitoring
      DB_SCHEMA: public
      DEBUG_LEVEL: INFO
      USER_SERVICE_URL: http://users-ms:8090
      SECRET_TOKEN: 6IBwdiQm6JUC7nCL8PEm9Y8O7D41XYoMlnPD4a3cXTd5AHEgQjdRZAsiao5ysm9hquHjvIuigm4ACGzwTEFC0A==
    depends_on:
      - rabbitmq
      - db
    networks:
      - monitoring-tool-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: monitoring-user
      POSTGRES_PASSWORD: monitoring
      POSTGRES_DB: monitoring_db
    volumes:
      - monitoring_db_data:/var/lib/postgresql/data
    networks:
      - monitoring-tool-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" 
      - "5672:5672"  
    networks:
      - monitoring-tool-network

networks:
  monitoring-tool-network:
    driver: bridge

volumes:
  monitoring_db_data:
    driver: local
