version: '3.8'

services:
  frontend:
    image: ghcr.io/monitoring-tool-app-unicauca/monitoring-tool-frontend-ms:latest
    container_name: monitoring-tool-frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - monitoring-tool-network
  users-ms:
    image: ghcr.io/monitoring-tool-app-unicauca/monitoring-tool-backend-users-ms:latest
    ports:
      - "8090:8090"
    environment:
      TZ: America/Bogota
      SPRING_PROFILES_ACTIVE: "docker"
      USERS_PORT: 8090
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: monitoring_db
      DB_USER: monitoring-user
      DB_PASSWORD: monitoring
      DB_SCHEMA: public
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      DEBUG_LEVEL: INFO
      JWT_EXPIRATION: 3600000
      JWT_SECRET: 6IBwdiQm6JUC7nCL8PEm9Y8O7D41XYoMlnPD4a3cXTd5AHEgQjdRZAsiao5ysm9hquHjvIuigm4ACGzwTEFC0A==
      NOTIFICATION_URL: http://ec2-13-218-48-57.compute-1.amazonaws.com:4200/auth/recovery-password
      NOTIFICATION_EXPIRES: 10
      ADMIN_EMAIL: julianndrb@gmail.com
      ADMIN_NAME: Paula Peña
      ADMIN_LASTNAME: App
      ADMIN_DOCUMENT: 1061226854
      ADMIN_PHONE: 3000000000
    depends_on:
      - rabbitmq
      - db
    networks:
      - monitoring-tool-network
  tracking-ms:
    image: ghcr.io/monitoring-tool-app-unicauca/monitoring-tool-backend-tracking-ms:latest
    ports:
      - "8092:8092"
    environment:
      TZ: America/Bogota
      SPRING_PROFILES_ACTIVE: "docker"
      TRACKING_PORT: 8092
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: monitoring_db
      DB_USERNAME: monitoring-user
      DB_PASSWORD: monitoring
      DB_SCHEMA: public
      DEBUG_LEVEL: INFO
      USER_SERVICE_URL: http://users-ms:8090
      SECRET_TOKEN: 6IBwdiQm6JUC7nCL8PEm9Y8O7D41XYoMlnPD4a3cXTd5AHEgQjdRZAsiao5ysm9hquHjvIuigm4ACGzwTEFC0A==
    depends_on:
      - rabbitmq
      - db
    networks:
      - monitoring-tool-network

      
  # Microservicio Notification
  notification-ms:
    image: ghcr.io/monitoring-tool-app-unicauca/monitoring-tool-backend-notification-ms:latest
    ports:
      - "8091:8091"
    environment:
      TZ: America/Bogota
      SPRING_PROFILES_ACTIVE: "docker"
      NOTIFICATION_PORT: 8091
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: julianndrb@gmail.com
      MAIL_PASSWORD: dxbcczoihmcgadny

      DEBUG_LEVEL: INFO
    depends_on:
      - users-ms
      - rabbitmq
    networks:
      - monitoring-tool-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: monitoring-user
      POSTGRES_PASSWORD: monitoring
      POSTGRES_DB: monitoring_db
    volumes:
      - monitoring_db_data:/var/lib/postgresql/data
    networks:
      - monitoring-tool-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" 
      - "5672:5672"  
    networks:
      - monitoring-tool-network

networks:
  monitoring-tool-network:
    driver: bridge

volumes:
  monitoring_db_data:
    driver: local
