name: Deploy Infra Stack on Dispatch Event

on:
  repository_dispatch:
    types: [deploy-from-ms]
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra repo
        uses: actions/checkout@v4

      - name: Copy SSH key and set permissions
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create infra folder on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.91.99.145 "mkdir -p ~/infra"

      - name: Copy docker-compose.yml to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@52.91.99.145:~/infra/docker-compose.yml

      - name: Deploy stack on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.91.99.145 "cd ~/infra && docker compose pull && docker compose up -d --remove-orphans"
