name: Deploy Infra Stack on Dispatch Event

on:
  repository_dispatch:
    types: [deploy-from-ms]
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra repo
        uses: actions/checkout@v4

      - name: Set up Docker Compose CLI
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull updated images
        run: |
          docker compose pull

      - name: Deploy stack
        run: |
          docker-compose up -d --remove-orphans

      - name: Notify deploy success
        run: echo "Infra stack updated with new image for service ${{ github.event.client_payload.service || github.ref_name }}"
